name: Cross-Platform Build and Release Zerofs

on:
  push:
    tags:
      - 'v*'    # Trigger on tags like v1.0.0
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: zerofs-linux
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'  # stable version recommended

    - run: |
        sudo apt update
        sudo apt install -y build-essential python3-dev gcc g++ upx
        pip install --upgrade pip nuitka
    - run: |
        nuitka zerofs.py --onefile --standalone --output-filename=zerofs-linux
        upx --best zerofs-linux

    - uses: actions/upload-artifact@v3
      with:
        name: zerofs-linux
        path: zerofs-linux

  build-windows:
    runs-on: windows-latest
    outputs:
      artifact-name: zerofs-windows.exe
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - run: |
        pip install --upgrade pip nuitka
    - run: |
        nuitka zerofs.py --onefile --standalone --output-filename=zerofs-windows.exe

    - uses: actions/upload-artifact@v3
      with:
        name: zerofs-windows.exe
        path: zerofs-windows.exe

  build-macos:
    runs-on: macos-latest
    outputs:
      artifact-name: zerofs-macos
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - run: |
        pip install --upgrade pip nuitka
    - run: |
        nuitka zerofs.py --onefile --standalone --output-filename=zerofs-macos

    - uses: actions/upload-artifact@main
      with:
        name: zerofs-macos
        path: zerofs-macos

  release:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
    - name: Download Linux binary
      uses: actions/download-artifact@main
      with:
        name: zerofs-linux
        path: release

    - name: Download Windows binary
      uses: actions/download-artifact@main
      with:
        name: zerofs-windows.exe
        path: release

    - name: Download macOS binary
      uses: actions/download-artifact@main
      with:
        name: zerofs-macos
        path: release

    - name: Create GitHub Release and upload binaries
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        files: release/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
