name: Cross-Platform Build and Release Zerofs

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    outputs:
      linux_path: ${{ steps.out.outputs.path }}
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies and build
      run: |
        sudo apt update
        sudo apt install -y build-essential python3-dev gcc g++ upx
        pip install --upgrade pip nuitka
        mkdir -p release
        nuitka zerofs.py --onefile --standalone --output-filename=release/zerofs-linux
        upx --best release/zerofs-linux

    - id: out
      run: echo "path=release/zerofs-linux" >> $GITHUB_OUTPUT

  build-windows:
    runs-on: windows-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    outputs:
      windows_path: ${{ steps.out.outputs.path }}
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies and build
      shell: cmd
      run: |
        pip install --upgrade pip nuitka
        mkdir release
        echo Y | nuitka zerofs.py --onefile --standalone --output-dir=release --output-filename=zerofs-windows.exe --windows-console-mode=disable --assume-yes-for-downloads

    - id: out
      shell: bash
      run: echo "path=release/zerofs-windows.exe" >> $GITHUB_OUTPUT

  build-macos:
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    outputs:
      macos_path: ${{ steps.out.outputs.path }}
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies and build
      run: |
        pip install --upgrade pip nuitka
        mkdir -p release
        nuitka zerofs.py --onefile --standalone --output-filename=release/zerofs-macos

    - id: out
      run: echo "path=release/zerofs-macos" >> $GITHUB_OUTPUT

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Copy Linux binary
      run: cp build-linux/release/zerofs-linux release/

    - name: Copy Windows binary
      run: cp build-windows/release/zerofs-windows.exe release/

    - name: Copy macOS binary
      run: cp build-macos/release/zerofs-macos release/

    - name: List binaries
      run: ls -la release/

    - name: Create GitHub Release and upload binaries
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        files: release/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
